import { Resolver, Query, Mutation, Args, Context } from '@nestjs/graphql';
import { Injectable, UseGuards } from '@nestjs/common';
import { PrismaService } from '../common/prisma.service';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { TripsService } from '../trips/trips.service';
import { PricingService } from '../pricing/pricing.service';
import { GeoService } from '../geo/geo.service';

/**
 * GraphQL API gateway — provides a single endpoint for mobile clients to
 * fetch exactly the data they need, avoiding REST over-fetching.
 *
 * Schema is auto-generated by NestJS GraphQL decorators. The gateway
 * delegates to existing services — no business logic is duplicated.
 *
 * Endpoint: POST /graphql
 * Playground: GET /graphql (dev only)
 */

// ─── Types ──────────────────────────────────────────────────────────────────

@injectable()
export class TripType {
  id: string;
  publicId: string;
  status: string;
  mode: string;
  pickupAddress: string;
  dropoffAddress: string;
  totalFare: number;
  currency: string;
  requestedAt: string;
  completedAt?: string;
}

@Injectable()
export class FareQuoteType {
  baseFare: number;
  distanceFare: number;
  timeFare: number;
  surgeMultiplier: number;
  totalFare: number;
  currency: string;
  distanceMeters: number;
  durationSeconds: number;
}

@Injectable()
export class UserType {
  id: string;
  phone: string;
  firstName: string;
  lastName: string;
  role: string;
  status: string;
}

// ─── Resolvers ──────────────────────────────────────────────────────────────

@Resolver(() => UserType)
export class UserResolver {
  constructor(private prisma: PrismaService) {}

  @Query(() => UserType, { nullable: true })
  @UseGuards(JwtAuthGuard)
  async me(@Context('req') req: any) {
    if (!req.user) return null;
    const user = await this.prisma.user.findUnique({ where: { id: req.user.id } });
    return user ? {
      id: user.id, phone: user.phone, firstName: user.firstName,
      lastName: user.lastName, role: user.role, status: user.status,
    } : null;
  }
}

@Resolver(() => TripType)
export class TripResolver {
  constructor(
    private prisma: PrismaService,
    private trips: TripsService,
  ) {}

  @Query(() => [TripType])
  @UseGuards(JwtAuthGuard)
  async myTrips(@Context('req') req: any, @Args('limit', { defaultValue: 20 }) limit: number) {
    const result = await this.trips.listForPassenger(req.user.id, 1, limit);
    return result.items.map((t: any) => ({
      id: t.id, publicId: t.publicId, status: t.status, mode: t.mode,
      pickupAddress: t.pickupAddress, dropoffAddress: t.dropoffAddress,
      totalFare: Number(t.totalFare), currency: t.currency,
      requestedAt: t.requestedAt, completedAt: t.completedAt,
    }));
  }

  @Query(() => TripType, { nullable: true })
  @UseGuards(JwtAuthGuard)
  async trip(@Args('id') id: string) {
    const trip = await this.trips.getById(id);
    if (!trip) return null;
    return {
      id: trip.id, publicId: trip.publicId, status: trip.status, mode: trip.mode,
      pickupAddress: trip.pickupAddress, dropoffAddress: trip.dropoffAddress,
      totalFare: Number(trip.totalFare), currency: trip.currency,
      requestedAt: trip.requestedAt, completedAt: trip.completedAt,
    };
  }

  @Mutation(() => TripType)
  @UseGuards(JwtAuthGuard)
  async requestTrip(
    @Context('req') req: any,
    @Args('pickupLat') pickupLat: number,
    @Args('pickupLng') pickupLng: number,
    @Args('dropoffLat') dropoffLat: number,
    @Args('dropoffLng') dropoffLng: number,
    @Args('mode') mode: string,
    @Args('vehicleType') vehicleType: string,
    @Args('paymentMethod') paymentMethod: string,
    @Args('pickupAddress', { nullable: true }) pickupAddress?: string,
    @Args('dropoffAddress', { nullable: true }) dropoffAddress?: string,
  ) {
    const result = await this.trips.request({
      passengerUserId: req.user.id,
      pickup: { lat: pickupLat, lng: pickupLng, address: pickupAddress },
      dropoff: { lat: dropoffLat, lng: dropoffLng, address: dropoffAddress },
      mode, vehicleType, paymentMethod,
    });
    return {
      id: result.tripId, publicId: result.publicId, status: 'REQUESTED', mode,
      pickupAddress: pickupAddress ?? '', dropoffAddress: dropoffAddress ?? '',
      totalFare: result.estimate.totalFare, currency: result.estimate.currency,
      requestedAt: new Date().toISOString(),
    };
  }
}

@Resolver(() => FareQuoteType)
export class PricingResolver {
  constructor(
    private pricing: PricingService,
    private geo: GeoService,
  ) {}

  @Query(() => FareQuoteType)
  async fareQuote(
    @Args('vehicleType') vehicleType: string,
    @Args('pickupLat') pickupLat: number,
    @Args('pickupLng') pickupLng: number,
    @Args('dropoffLat') dropoffLat: number,
    @Args('dropoffLng') dropoffLng: number,
    @Args('city', { nullable: true, defaultValue: 'Addis Ababa' }) city?: string,
  ) {
    const quote = await this.pricing.getQuote({
      vehicleType,
      pickup: { lat: pickupLat, lng: pickupLng },
      dropoff: { lat: dropoffLat, lng: dropoffLng },
      city,
    });
    return quote;
  }
}
